export {
  UUID,
  loginSchema,
  registerSchema,
  changePasswordSchema,
  profileSchema,
  createClassSchema,
  addStudentSchema,
  studentNoteSchema,
  createHomeworkSchema,
  submissionStatusSchema,
  attendanceStatusSchema,
  saveAttendanceSchema,
  createMeetingSchema,
  createExamSchema,
  createCurriculumProgressSchema,
  curriculumStatusSchema,
  updateSchoolSchema,
} from '@/lib/validation'
